export const TEACHER: string = 'teacher';
export const MAX_EMPLOYEE_ID_LENGTH = 8
export const MAX_PASSWORD_LENGTH = 20;
export const MIN_PASSWORD_LENGTH = 8;
export const PHONE_LENGTH = 11;
export const LOGIN_TEACHERINFO_KEY = 'teacherInfo';
export const LOGIN_ADMINISTRATORINFO_KEY = 'administratorInfo';
export const ADMINISTRATOR_ID = 'administratorId';
export const TEACHER_ID = 'teacherId';
export const ADMINISTRATOR_PASSWORD = 'aPassword';
export const TEACHER_PASSWORD = 'tPassword';